### ISSUE TITLE
warning and some build errs when installing plugin in ue5.7

### ISSUE THREAD

**Issue by siq10** [ColtonWilley/ue-llm-toolkit#4]
Hi, First of all, maybe i misunderstood, this plugin should work on 5.7, i installed 5.7 but plugin added gives warning saying plugin was made using 5.6. 
Following warn + errors show up on build

warning : Plugin 'UELLMToolkit' does not list plugin 'Interchange' as a dependency, but module 'UELLMToolkit' depends on module 'InterchangePipelines'.

>D:\ue_projects\2dnew\glovosim\Plugins\UELLMToolkit\Source\UELLMToolkit\Private\RetargetEditor.cpp(539,42): error C2039: 'AddBoneToSkeleton': is not a member of 'FRetargetEditor'
1>  TSharedPtr<FJsonObject> FRetargetEditor::AddBoneToSkeleton(const FString& SkeletonPath,
1>                                           ^
1>  D:\ue_projects\2dnew\glovosim\Plugins\UELLMToolkit\Source\UELLMToolkit\Private\RetargetEditor.h(24,7): note: see declaration of 'FRetargetEditor'
1>  class FRetargetEditor
1>        ^
1>D:\ue_projects\2dnew\glovosim\Plugins\UELLMToolkit\Source\UELLMToolkit\Private\RetargetEditor.cpp(544,24): error C3861: 'LoadSkeletonFromPath': identifier not found
1>  	USkeleton* Skeleton = LoadSkeletonFromPath(SkeletonPath, LoadError);
1>  	                      ^
1>D:\ue_projects\2dnew\glovosim\Plugins\UELLMToolkit\Source\UELLMToolkit\Private\RetargetEditor.cpp(547,10): error C3861: 'ErrorResult': identifier not found
1>  		return ErrorResult(LoadError);
1>  		       ^
1>D:\ue_projects\2dnew\glovosim\Plugins\UELLMToolkit\Source\UELLMToolkit\Private\RetargetEditor.cpp(554,10): error C3861: 'ErrorResult': identifier not found
1>  		return ErrorResult(FString::Printf(TEXT("Bone '%s' already exists in skeleton"), *BoneName));
1>  		       ^
1>D:\ue_projects\2dnew\glovosim\Plugins\UELLMToolkit\Source\UELLMToolkit\Private\RetargetEditor.cpp(560,10): error C3861: 'ErrorResult': identifier not found
1>  		return ErrorResult(FString::Printf(TEXT("Parent bone '%s' not found in skeleton"), *ParentBoneName));
1>  		       ^
1>D:\ue_projects\2dnew\glovosim\Plugins\UELLMToolkit\Source\UELLMToolkit\Private\RetargetEditor.cpp(587,42): error C2039: 'CopyBoneTracks': is not a member of 'FRetargetEditor'
1>  TSharedPtr<FJsonObject> FRetargetEditor::CopyBoneTracks(const FString& SourceAnimPath,
1>                                           ^
1>  D:\ue_projects\2dnew\glovosim\Plugins\UELLMToolkit\Source\UELLMToolkit\Private\RetargetEditor.h(24,7): note: see declaration of 'FRetargetEditor'
1>  class FRetargetEditor
1>        ^
1>D:\ue_projects\2dnew\glovosim\Plugins\UELLMToolkit\Source\UELLMToolkit\Private\RetargetEditor.cpp(591,30): error C3861: 'LoadAnimSequence': identifier not found
1>  	UAnimSequence* SourceAnim = LoadAnimSequence(SourceAnimPath, LoadError);
1>  	                            ^
1>D:\ue_projects\2dnew\glovosim\Plugins\UELLMToolkit\Source\UELLMToolkit\Private\RetargetEditor.cpp(592,26): error C3861: 'ErrorResult': identifier not found
1>  	if (!SourceAnim) return ErrorResult(LoadError);
1>  	                        ^
1>D:\ue_projects\2dnew\glovosim\Plugins\UELLMToolkit\Source\UELLMToolkit\Private\RetargetEditor.cpp(594,30): error C3861: 'LoadAnimSequence': identifier not found
1>  	UAnimSequence* TargetAnim = LoadAnimSequence(TargetAnimPath, LoadError);
1>  	                            ^
1>D:\ue_projects\2dnew\glovosim\Plugins\UELLMToolkit\Source\UELLMToolkit\Private\RetargetEditor.cpp(595,26): error C3861: 'ErrorResult': identifier not found
1>  	if (!TargetAnim) return ErrorResult(LoadError);
1>  	                        ^
1>D:\ue_projects\2dnew\glovosim\Plugins\UELLMToolkit\Source\UELLMToolkit\Private\RetargetEditor.cpp(598,27): error C3861: 'ErrorResult': identifier not found
1>  	if (!SourceModel) return ErrorResult(TEXT("Source animation has no data model"));
1>  	                         ^
1>D:\ue_projects\2dnew\glovosim\Plugins\UELLMToolkit\Source\UELLMToolkit\Private\RetargetEditor.cpp(602,27): error C3861: 'ErrorResult': identifier not found
1>  	if (!TargetModel) return ErrorResult(TEXT("Target animation has no data model"));

Short log of errors:
'AddBoneToSkeleton': is not a member of 'FRetargetEditor'
'LoadSkeletonFromPath': identifier not found
'ErrorResult': identifier not found
'ErrorResult': identifier not found
'ErrorResult': identifier not found
'CopyBoneTracks': is not a member of 'FRetargetEditor'
'LoadAnimSequence': identifier not found
'ErrorResult': identifier not found
'LoadAnimSequence': identifier not found
'ErrorResult': identifier not found
'ErrorResult': identifier not found
'ErrorResult': identifier not found

Am i missing something? I also see engine version for the plugin is 5.6, is this actually meant for 5.6? Or as mentioned in readme, for 5.7?

**Comment by siq10** [comment]
seems build is successful after adding these 2 in  **RetargetEditor.h** (method decl were missing in header for me). If they are missing in repo i imagine it would be a good idea to add them, for me plugin crashes project otherwise

```
	static TSharedPtr<FJsonObject> AddBoneToSkeleton(const FString& SkeletonPath, const FString& BoneName, const FString& ParentBoneName, const FVector& Position, const FQuat& Rotation);

	static TSharedPtr<FJsonObject> CopyBoneTracks(const FString& SourceAnimPath, const FString& TargetAnimPath, const TArray<FString>& BoneNames);
```

**Comment by ColtonWilley** [comment]
@siq10 Thank you for bringing this to my attention. I believe this is fixed in commit https://github.com/ColtonWilley/ue-llm-toolkit/commit/d6b6923cc81f5cf4d093a74302388297bd8e594e . Please try the latest master and let me know if that works for you

**Comment by ColtonWilley** [comment]
@siq10 that commit did accidentally remove some domain docs, everything should be fixed on master though
